### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by KekkyShmekky** [TankNut/MechAssault#1]
```
[mechassault] addons/mechassault/lua/entities/ma2_mech/sh_weapons.lua:23: attempt to call method 'LagCompensation' (a nil value)
  1. GetTargetLock - addons/mechassault/lua/entities/ma2_mech/sh_weapons.lua:23
   2. DrawHUD - addons/mechassault/lua/entities/ma2_mech/cl_hud.lua:31
    3. v - addons/mechassault/lua/autorun/mechassault_autorun.lua:121
     4. unknown - lua/includes/modules/hook.lua:84 (x2)

```

Also mechs that don't work, unless some(or all) of them are no-clipped into or entered at different angles, unless the latter is intended behavior:

Atlas, Blood Asp, Prometheus, Star Adder, Bowman, Loki, Mad Cat, Nova Cat, Summoner, Wendigo, Corvus, Belial, Mad Dog, Vulture

**Comment by TankNut** [comment]
You have to enter the mechs by hitting +use on any part that the game considers solid, try the legs/feet if the hip area doesn't work, it's a model issue.

**Comment by KekkyShmekky** [comment]
Okay well there's also a weird glitch where if I enter a mech wrong, it won't let me operate it or leave until it's removed.
